"""Evidence-based identity consistency checks; no adverse inference from missing data."""
from app.core.enums import EvidenceState
from app.core.normalization import normalize_title
from app.providers.base import NormalizedEvidence


def identity_conflicts(journal_title: str, publisher: str | None, domain: str | None, evidence: list[NormalizedEvidence]) -> list[NormalizedEvidence]:
    findings: list[NormalizedEvidence] = []
    expected_title = normalize_title(journal_title)
    expected_publisher = normalize_title(publisher or "")
    expected_domain = (domain or "").lower().removeprefix("www.")
    for item in evidence:
        title = item.value.get("title")
        if title and expected_title and normalize_title(str(title)) != expected_title:
            findings.append(NormalizedEvidence("identity_audit", "identity", {"field": "title", "expected": journal_title, "observed": title, "provider": item.provider}, EvidenceState.CONTRADICTED, 0.8, item.source_url))
        observed_publisher = item.value.get("publisher")
        if observed_publisher and expected_publisher and normalize_title(str(observed_publisher)) != expected_publisher:
            findings.append(NormalizedEvidence("identity_audit", "publisher", {"field": "publisher", "expected": publisher, "observed": observed_publisher, "provider": item.provider}, EvidenceState.CONTRADICTED, 0.68, item.source_url))
        observed_url = item.value.get("journal_url")
        if observed_url and expected_domain and expected_domain not in str(observed_url).lower():
            findings.append(NormalizedEvidence("identity_audit", "domain", {"field": "domain", "expected": domain, "observed_url": observed_url, "provider": item.provider}, EvidenceState.CONTRADICTED, 0.75, item.source_url))
    # De-duplicate equivalent findings generated by multiple source rows.
    unique: dict[tuple[str, str], NormalizedEvidence] = {}
    for finding in findings:
        unique[(finding.evidence_type, str(finding.value))] = finding
    return list(unique.values())
