from enum import StrEnum


class EvidenceState(StrEnum):
    VERIFIED = "VERIFIED"
    CONTRADICTED = "CONTRADICTED"
    NOT_VERIFIED = "NOT_VERIFIED"
    NOT_OBSERVED = "NOT_OBSERVED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNKNOWN = "UNKNOWN"
    STALE = "STALE"


class AssessmentLabel(StrEnum):
    LOW_RISK = "LOW_RISK"
    SOME_CONCERNS = "SOME_CONCERNS"
    HIGH_RISK = "HIGH_RISK"
    IDENTITY_CONFLICT = "IDENTITY_CONFLICT"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class JournalStage(StrEnum):
    NEW = "NEW"
    ESTABLISHING = "ESTABLISHING"
    ESTABLISHED = "ESTABLISHED"
    CEASED = "CEASED"
    UNKNOWN = "UNKNOWN"

